export const GENERATE_PROBLEM = 'GENERATE_PROBLEM';
export const ADD_TO_SCORE = 'ADD_TO_SCORE';
export const REPSOND_TO_SUBMISSION = 'REPSOND_TO_SUBMISSION';
export const CHANGE_PAGE = "CHANGE_PAGE";
export const SET_HIGH_SCORE = "SET_HIGH_SCORE";
export const SET_USERNAME = "SET_USERNAME";